# Generated by Django 5.2.10 on 2026-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('Salary', models.FloatField()),
                ('join_date', models.DateField()),
                ('post', models.CharField(max_length=100)),
                ('Experience', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
