# Generated by Django 5.2.10 on 2026-02-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employees',
        ),
    ]
