# Generated by Django 5.2.10 on 2026-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeePosition', models.CharField(max_length=100)),
                ('employeeSalary', models.FloatField()),
                ('employeeExperience', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productStock', models.IntegerField()),
                ('productDiscount', models.FloatField(null=True)),
                ('productColor', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Resturants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturantName', models.CharField(max_length=100)),
                ('resturantLocation', models.CharField(max_length=100)),
                ('resturantRating', models.FloatField()),
                ('resturantType', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'resturants',
            },
        ),
    ]
