# Generated by Django 5.2.10 on 2026-02-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='book',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membercard',
            name='member',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberCard',
        ),
        migrations.DeleteModel(
            name='Student2',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
